name: Run Linter and Tests
on:
  - push
  - pull_request

jobs:
  execute_linter_and_tests:
    name: Install requirements and execute linter, and tests
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Execute flake8 linter
        run: flake8
